[downloads]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/downloads
	skip smb perm=yes
	comment=""
[homes]
	recycle bin admin only=yes
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=yes
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/homes
	skip smb perm=yes
	comment="user home"
[music]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/music
	skip smb perm=yes
	comment="System default shared folder"
[photo]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,PhotoStation,@administrators,admin,nobody
	browseable=yes
	read list=nobody,Eline Bollen,nobody
	hide unreadable=yes
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,Eline Bollen,@administrators,PhotoStation,admin,nobody
	ftp disable list=no
	edit synoacl=no
	writeable=yes
	guest ok=yes
	path=/volume1/photo
	skip smb perm=no
	comment="System default shared folder"
[Plex upload]
	recycle bin admin only=yes
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=yes
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/Plex upload
	skip smb perm=yes
	comment=""
[PlexMediaServer]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/PlexMediaServer
	skip smb perm=yes
	comment=""
[sonarr-downloads]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=no
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/sonarr-downloads
	skip smb perm=yes
	comment="Sonarr Downloads"
[surveillance]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,SurveillanceStation,@administrators,admin,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=no
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,@administrators,admin,SurveillanceStation,nobody
	ftp disable list=no
	edit synoacl=no
	writeable=yes
	guest ok=yes
	path=/volume1/surveillance
	skip smb perm=no
	comment="System default shared folder"
[video]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	read list=nobody,nobody
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	valid users=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	writeable=yes
	guest ok=yes
	path=/volume1/video
	skip smb perm=yes
	comment="System default shared folder"
