[global]
	printcap name=cups
	winbind enum groups=yes
	include=/var/tmp/nginx/smb.netbios.aliases.conf
	min protocol=NT1
	security=user
	local master=no
	realm=*
	passdb backend=smbpasswd
	printing=cups
	max protocol=SMB3
	winbind enum users=yes
	load printers=yes
	workgroup=WORKGROUP
